name: Slicebelgium
favicon: null
layout_spectrum: 0.8080735206604004
typography_spectrum: 0.8806837245356292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8227767744101584
  lightness: 0.7065012026578188
  saturation: 0.05260280054062605
  rhythmicContrast: 0.30281826108694077
purpose: []
